### PR TITLE
Bump min SDK to fix tests

### PR DESCRIPTION
**Pull request by kevmoo**
Use chrome instead of firefox for browser tests on travis

### CODE REVIEW

**Comment by natebosch** [comment]
We could fix the tests instead...

**Comment by kevmoo** [comment]
> We could fix the tests instead...

Isn't this due to an SDK bug? That's my memory...

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/test/issues/1141

**Comment by natebosch** [comment]
Yes, this is caused by an SDK bug. Rather than ignoring the fact that there is a version of `package:test` in the wild that no one can use on that SDK we should publish a version that works, then bump the dep in test.

https://github.com/dart-lang/test/pull/1143

**Comment by kevmoo** [comment]
Good idea!

**Pull request closed without merging**
