### PR TITLE
add default charset of application/json to utf-8

### PR DESCRIPTION
**Pull request by wanjm**
add default charset of application/json to utf-8. as. https://github.com/dart-lang/http_parser/issues/39

### CODE REVIEW

**Comment by wanjm** [comment]
@googlebot I signed it!

**Comment by wanjm** [comment]
any one help me!

**Comment by Wouter12** [comment]
Any idea on when this is gonna be merged? The CI build was canceled it seems

**Comment by kevmoo** [comment]
please try rebasing and pushing your fix. That should re-run CI. We've moved CI providers to GitHub

**Pull request closed without merging**
