### PR TITLE
add default charset of application/json to utf8

### PR DESCRIPTION
**Pull request by wferem1**
PR for #39

### CODE REVIEW

**Comment by wferem1** [comment]
@googlebot I signed it!

**Comment by wferem1** [comment]
@kevmoo since the other PR is not working, i created a new

**Comment by kevmoo** [comment]
We'll need tests here, too.
CC @natebosch – I'm really not working

**Comment by natebosch** [comment]
I'm not sure if it makes sense to set a default in this library since it will be a behavior difference against the HTTP parsing that happens in the SDK. We're also looking at whether it makes sense to default to UTF8 decoding in `packge:http` when reading `response.body` as a string: https://github.com/dart-lang/http/issues/175

cc @lrhn - do you have any thoughts on the right place for this type of defaulting?

**Comment by wferem1** [comment]
I added a test for the default charset.
I understand that this may not seem the right place to do this defaulting, so you may close this PR if it is done in the http package.

**Comment by lrhn** [comment]
I don't think this is where I'd insert a default (if anywhere). Modifying the source data early in the process prevents later code from recognizing that there originally was no `charset` and do something customized in that case.

I'd rather do something at the point where the `charset` is consumed. That is, if we try to get an encoding for the body, and the media type has no `charset` parameter, *then* I'd see if there is a default encoding for that particular media type.
If there isn't, I'm inclined to actually refuse to decode without an encoding being provided by the user, rather than defaulting to *something* (especially if that something is Latin-1, because that encoding is irrefutable, and will accept any incoming bytes whether intended as Latin-1 or not).

**Comment by wferem1** [comment]
@lrhn I agree with that reasoning, I will close this PR, since this is already being discussed in dart-lang/http#175

**Pull request closed without merging**
